from TimeSeriesDataAnalysisLib.interface.untrainable_stored_v2_0.structure import DataInfoObject,VERSION,ResearchArrayDataObject,MarkObject,ArrayDataObject,AnnotationObject,TimeSeriesStepFlag,EventObject,ControlStatusObject,SubArrayDataObject,SubObjectDataObject
from TimeSeriesDataAnalysisLib.interface.untrainable_stored_v2_0.data_provider import ResearchArrayDataProvider,TimeSeriesMode


